#!/bin/bash
cd ../linden/indra/newview
DIFF_DEST='/src/snowglobe2.0/indra/newview'
RESULT_DIR='/src/imrudence-sqrt2-proposal/work/newview/'
for x in *.h; do
	diff -u $x $DIFF_DEST/$x > $RESULT_DIR/$x.diff

done

for x in *.cpp; do

	diff -u $x $DIFF_DEST/$x > $RESULT_DIR/$x.diff

done